<a href="https://colab.research.google.com/github/zeeshan3106/Machine-Learning/blob/main/AdaBoost%20Classification%20(Manual).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [261]:
import pandas as pd

data = {

    'Rooms': [3, 2, 4, 1, 3, 5, 2, 4],

    'Distance_to_CBD': [4.2, 12.5, 5.1, 2.8, 18.0, 8.3, 22.1, 3.5],

    'Is_Expensive': [1, 0, 1, 0, 0, 1, 0, 1]

}
import pandas as pd
df = pd.DataFrame(data)
print(f"Total rows in dataset: {len(df)}")
data = pd.DataFrame(data)
data
X = data.drop('Is_Expensive',axis=1)
y = data['Is_Expensive']
y

Total rows in dataset: 8

0    1
1    0
2    1
3    0
4    0
5    1
6    0
7    1
Name: Is_Expensive, dtype: int64

In [262]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
tree = DecisionTreeClassifier(max_depth=1)
X_train = tree.fit(X,y)
y_pred = tree.predict(X)
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred)*100

87.5

In [263]:
X['weight'] = 1/X.shape[0]
X

   Rooms  Distance_to_CBD  weight
0      3              4.2   0.125
1      2             12.5   0.125
2      4              5.1   0.125
3      1              2.8   0.125
4      3             18.0   0.125
5      5              8.3   0.125
6      2             22.1   0.125
7      4              3.5   0.125

In [264]:
X['Y_pred']=y_pred
X['Y']=y
import numpy as np

X

   Rooms  Distance_to_CBD  weight  Y_pred  Y
0      3              4.2   0.125       1  1
1      2             12.5   0.125       0  0
2      4              5.1   0.125       1  1
3      1              2.8   0.125       1  0
4      3             18.0   0.125       0  0
5      5              8.3   0.125       1  1
6      2             22.1   0.125       0  0
7      4              3.5   0.125       1  1

In [265]:
X
error = 0.125
alpha = 0.5*np.log((1-error)/(error))
alpha

np.float64(0.9729550745276566)

In [266]:
new_weight = 0.125 * np.exp(alpha)
new_weight
C_new_weight = 0.125*np.exp(-alpha)
C_new_weight

np.float64(0.04724555912615341)

In [267]:
import numpy as np

def function(row, apple, ball):
    # Check the specific row's Y and Y_pred values
    if row['Y'] == row['Y_pred']:
        return ball                       # Correct prediction (C_new_weight)
    else:
        return 0.125 * np.exp(apple)      # Incorrect prediction (new_weight)

apple = alpha
ball = C_new_weight

# Pandas loops through row-by-row automatically
X['new_weight'] = X.apply(function, axis=1, args=(apple, ball))
X

   Rooms  Distance_to_CBD  weight  Y_pred  Y  new_weight
0      3              4.2   0.125       1  1    0.047246
1      2             12.5   0.125       0  0    0.047246
2      4              5.1   0.125       1  1    0.047246
3      1              2.8   0.125       1  0    0.330719
4      3             18.0   0.125       0  0    0.047246
5      5              8.3   0.125       1  1    0.047246
6      2             22.1   0.125       0  0    0.047246
7      4              3.5   0.125       1  1    0.047246

In [268]:
X['new_weight'] = X['new_weight']/X['new_weight'].sum()
X.head(1)

   Rooms  Distance_to_CBD  weight  Y_pred  Y  new_weight
0      3              4.2   0.125       1  1    0.071429

In [269]:
X['Upper']=np.cumsum(X['new_weight'])
X['Lower']=X['Upper']-X['new_weight']

X

   Rooms  Distance_to_CBD  weight  Y_pred  Y  new_weight     Upper     Lower
0      3              4.2   0.125       1  1    0.071429  0.071429  0.000000
1      2             12.5   0.125       0  0    0.071429  0.142857  0.071429
2      4              5.1   0.125       1  1    0.071429  0.214286  0.142857
3      1              2.8   0.125       1  0    0.500000  0.714286  0.214286
4      3             18.0   0.125       0  0    0.071429  0.785714  0.714286
5      5              8.3   0.125       1  1    0.071429  0.857143  0.785714
6      2             22.1   0.125       0  0    0.071429  0.928571  0.857143
7      4              3.5   0.125       1  1    0.071429  1.000000  0.928571

In [270]:
def function(X):
  incides = []
  for i in range(X.shape[0]):
    a = np.random.random()
    for index, row in X.iterrows():

      if row['Upper']>a and a > row['Lower']:
        incides.append(index)
  return incides

X = X
iv = function(X)
iv

[3, 6, 5, 3, 0, 3, 3, 3]

In [271]:
Adab1 = X.iloc[iv,[0,1,2,4]]
Adab1

   Rooms  Distance_to_CBD  weight  Y
3      1              2.8   0.125  0
6      2             22.1   0.125  0
5      5              8.3   0.125  1
3      1              2.8   0.125  0
0      3              4.2   0.125  1
3      1              2.8   0.125  0
3      1              2.8   0.125  0
3      1              2.8   0.125  0

In [272]:
X = Adab1
X = X.drop(['weight','Y'],axis=1)
X
y = Adab1['Y']
y
tree2 = tree.fit(X,y)
y_pred = tree.predict(X)
from sklearn.metrics import accuracy_score
a = accuracy_score(y,y_pred)*100
X["Y"]=y
X["Y_pred"]=y_pred
a

100.0

In [273]:
np.sign(alpha*1)

np.float64(1.0)