<a href="https://colab.research.google.com/github/zeeshan3106/Machine-Learning/blob/main/AdaBoost%20Classification%20(Week%20Learner).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

data = {
    'Rooms': [3, 2, 4, 1, 3, 5, 2, 4],
    'Distance_to_CBD': [4.2, 12.5, 5.1, 2.8, 18.0, 8.3, 22.1, 3.5],
    'Is_Expensive': [1, 0, 1, 0, 0, 1, 0, 1]
}
data = pd.DataFrame(data)
data
X = data.drop('Is_Expensive',axis=1)
y = data['Is_Expensive']
y

0    1
1    0
2    1
3    0
4    0
5    1
6    0
7    1
Name: Is_Expensive, dtype: int64

In [28]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth = 1)
X_train = tree.fit(X,y)
y_pred = tree.predict(X)
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred)*100

87.5

In [37]:
X['weight'] = 1/X.shape[0]
X

   Rooms  Distance_to_CBD  weight
0      3              4.2   0.125
1      2             12.5   0.125
2      4              5.1   0.125
3      1              2.8   0.125
4      3             18.0   0.125
5      5              8.3   0.125
6      2             22.1   0.125
7      4              3.5   0.125

In [43]:
X['Y_pred']=y_pred
X['Y']=y
import numpy as np

X

   Rooms  Distance_to_CBD  weight  Y_pred  Y
0      3              4.2   0.125       1  1
1      2             12.5   0.125       0  0
2      4              5.1   0.125       1  1
3      1              2.8   0.125       1  0
4      3             18.0   0.125       0  0
5      5              8.3   0.125       1  1
6      2             22.1   0.125       0  0
7      4              3.5   0.125       1  1

In [50]:
X
error = 0.125
alpha = 0.5*np.log((1-error)/(error))
alpha

np.float64(0.9729550745276566)

In [54]:
new_weight = 0.125 * np.exp(alpha)
new_weight
C_new_weight = 0.125*np.exp(-alpha)
C_new_weight

np.float64(0.04724555912615341)